Transform: 'AWS::Serverless-2016-10-31'
Parameters:
    Environment: 
        Type: String  
        Description: Name of the environment for which the resources are getting created
Resources:
    GetSAMPartyCount:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.test1
            Runtime: nodejs8.10
            Role:
              Fn::ImportValue:
                !Join ['-', [!Ref 'Environment', 'LambdaTrustRole']] 
            Events:
              GetEvent:
                Type: Api
                Properties:
                  Path: /sam
                  Method: get
                  StageName: mine
